name: .NET

on:
  push:
    branches: [ "zx" ]
  pull_request:
    branches: [ "zx" ]

jobs:
    build:
    runs-on: windows-latest
    defaults:
    run:
    working-directory: ./Lab2/ICT3103_Calculator
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      - name: NUnit Tests
    working-directory: ICT3101_Calculator.UnitTests/
    run: dotnet test --no-build --verbosity normal
    - name: SpecFLow Tests
    working-directory: SpecFlowCalculatorTests/
    run: dotnet test --no-build --verbosity normal
